### ISSUE TITLE
Error: The "path" argument must be of type string. Received undefined TypeError: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by zhenzhen1022** [web-infra-dev/midscene-example#22]
@midscene/web0.8.6，如题
    Error: The "path" argument must be of type string. Received undefined
    TypeError: The "path" argument must be of type string. Received undefined

        at join (node:path:461:7)
        at getTmpDir (node_modules\@midscene\core\dist\lib\utils.js:243:42)

**Comment by yuyutaotao** [comment]
运行的是什么命令？

**Comment by yuyutaotao** [comment]
1. 更新到最新版本试一下
2. 如果问题依旧，麻烦提供更详细的复现信息，在这里重开一个 issue: https://github.com/web-infra-dev/midscene/issues
