### ISSUE TITLE
Error: Timed out after waiting 30000ms

### ISSUE THREAD

**Issue by skuramatata** [web-infra-dev/midscene-example#23]
<img width="602" alt="Image" src="https://github.com/user-attachments/assets/3ed4cad7-95a5-40d7-a801-95a793eae27d" />
每次操作完输入框，回车跳到新页面之后就不动了
然后报错Error: Timed out after waiting 30000ms

**Comment by yuyutaotao** [comment]
如果创建了新的页面，需要用新的 Page 实例去创建 agent 对象。看下是不是这个问题。

**Comment by yuyutaotao** [comment]
update: 确实是有个一个网络等待 （waitUntilNetworkIdle）没 catch，预计下周发布修复

**Comment by yuyutaotao** [comment]
已经在最新版本中修复
